### ISSUE TITLE
Limit Solution's name length

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/tb-eagle-console#119]
This name is been used to create a project in GCP. The UI should restrict the Solution input's name in the FORM to 30 characters.

**Comment by Salles-FA** [comment]
@sunderhill-gft Please confirm if:

1. 30 characters is the limitation to set in the UI
1. or it is the total length (with the final hash included at the end of the project string)

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/14

**Comment by sunderhill-gft** [comment]
The limits on GCP folder names are mentioned [here](https://cloud.google.com/resource-manager/docs/creating-managing-folders)
In summary:
The name may contain letters, digits, spaces, hyphens and underscores.
The folder's display name must start and end with a letter or digit.
The name must be 30 characters or less.
The name must be distinct from all other folders that share its parent.
