### ISSUE TITLE
Allow Dev Users to see TEAMS and USER 

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/tb-eagle-console#140]
**Is your feature request related to a problem? Please describe.**
Currently only Admin Users have access to Administration area.

**Describe the solution you'd like**
Allow Dev Users to see TEAMS and USER sidenav menu items within Administration menu area.

**Describe alternatives you've considered**
Keep the Administration Menu hidden to Dev Users and show the TEAMS and USER menu items within the "Mission Control" menu.

**Additional context**

- If the User does not belong to any TEAM, then the Welcome Screen should redirect the User to request to join.
- Related Issues: https://github.com/tranquilitybase-io/tb-eagle-console/issues/116

**Comment by andy12838729** [comment]
Probably should see the Settings menu also (will be different content for Devs)

**Comment by RavMucha** [comment]
Fixed. Dev users view now:
![image](https://user-images.githubusercontent.com/26556392/83396417-3d139100-a3fc-11ea-9457-a109f3ad2540.png)

**Comment by Salles-FA** [comment]
Cant close without merging into master.
