### ISSUE TITLE
[BUG] mat-sidenav-content creates blank space on bottom

### ISSUE THREAD

**Issue by RavMucha** [tranquilitybase-io/tb-eagle-console#144]
**Describe the bug**
The mat-sidenav-content container is fixed to width of 89vh, which creates a blank bar on the bottom on some screen proportions.

**To Reproduce**
1. Go to 'Landing Zone'
2. Click on 'ctrl + mouse scroll down to zoom out'
3. Use either DevTools inspector or look at the websites scrollbar being shorter, than the page.

**Expected behavior**
The content/container should scale exactly to fit the working area, starting from the end of the top toolbar and until the very end of the page's visible area.

**Screenshots**
![image](https://user-images.githubusercontent.com/26556392/83395936-70095500-a3fb-11ea-8af7-e4b6ddecba1e.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version  83.0.4103.61

**Additional context**

**Comment by RavMucha** [comment]
Fixed the CSS, added variables and calc functions:

![image](https://user-images.githubusercontent.com/26556392/83396775-c88d2200-a3fc-11ea-937b-6997dfdd4fe9.png)

**Comment by Salles-FA** [comment]
Can't close without merging into master.
