### ISSUE TITLE
[Feature] Make the Workspace optional

### ISSUE THREAD

**Issue by andy12838729** [tranquilitybase-io/tb-eagle-console#147]
**Is your feature request related to a problem? Please describe.**
Currently every solution requires a Workspace. Sometimes this may not be needed if a simple sandbox activator is being deployed.

**Describe the solution you'd like**
When setting up a Solution, if the user does not specify any DevOps infrastructure, then do not create a Workspace project.

**Describe alternatives you've considered**

**Additional context**

**Comment by Salles-FA** [comment]
Done
