### ISSUE TITLE
Implement TEAMS 'view' screen

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/tb-eagle-console#160]
- Using the same layout of the existing `view` screens.
- Using `api/team/{oid}` GET REST call
- Using `api/teammembers/{oid}` GET REST call

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/23

**Comment by andy12838729** [comment]
Should be able to have an "Add Member" button if you are a TeamAdmin.
