### ISSUE TITLE
[BUG] changing showWelcome via PUT breaks the DB

### ISSUE THREAD

**Issue by RavMucha** [tranquilitybase-io/tb-eagle-console#166]
**Describe the bug**
When the user checks the checkbox for not showing the Welcome Screen, and a PUT is dispatched to change the showWelcome boolean value on the user's account, that breaks the DataBase. After logout it no longer accepts that user's credentials, responding with a 500 server error. 
**To Reproduce**
1. Go to 'check the checkbox on the Welcome Screen, click'
2. Click on the 'Get Started / Solutions' WS button to close the WS modal.
3. Log out and try to log back in.

**Expected behavior**
The showWelcome value is just changed in the DB with no other consequence.

**Screenshots**
![image](https://user-images.githubusercontent.com/26556392/84151976-5c499880-aa64-11ea-8d1e-7574cdc680ab.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version  83.0.4103.97

**Additional context**

**Comment by karwootang-gft** [comment]
Hi - You need to use the below payload, containing the id, at the moment without the id the endpoint will create a new row, and the login will fail because 2 users are found with the same email:

  { 
    "id": 1,
    "showWelcome": true
  }
