### ISSUE TITLE
[Feature] Notifications functionality for activator

### ISSUE THREAD

**Issue by kwicherska** [tranquilitybase-io/tb-eagle-console#199]
**Is your feature request related to a problem? Please describe.**
A notification functionality - when user request an access to the activator admin gets a notification which can be clicked and direct to specific activator - there admin can grant or deny access and user will get a notification about the state of his previous request.

**Describe the solution you'd like**
Apply adjusted parts of angular material for the view (there is no ready notification in material).

**Describe alternatives you've considered**

**Additional context**

**Comment by andy12838729** [comment]
If there are multiple Admin users, they should all receive the message. Likewise when a message goes back to a Team, all members should receive the message.
