### ISSUE TITLE
[BUG] When adding an activator to a new solution, "Deploy All" is inactive

### ISSUE THREAD

**Issue by andy12838729** [tranquilitybase-io/tb-eagle-console#204]
**Describe the bug**

**To Reproduce**
1. create a solution
2. deploy it
3. add an activator
![image](https://user-images.githubusercontent.com/53095823/86781559-f85fc300-c055-11ea-88f5-fd1e392b548f.png)

**Expected behavior**
Deploy All should be available

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Salles-FA** [comment]
This issue is being closed because this bug no longer exists in current running version.
