### ISSUE TITLE
[Feature] Adapt Activator Store to new version of API

### ISSUE THREAD

**Issue by Aparad** [tranquilitybase-io/tb-eagle-console#228]
**Is your feature request related to a problem? Please describe.**
Update the Activators templates to match current json:
`{
  "accessRequestedBy": null,
  "accessRequestedById": null,
  "activator": "Single Region Kubernetes",
  "activatorMetadata": {
    "activatorLink": "",
    "category": "Web application",
    "description": "CMS Web Application activator",
    "id": 1,
    "lastUpdated": "2020-05-12 08:29:07",
    "name": "CMS Web App",
    "platforms": [
      {
        "id": 1,
        "value": "GCP"
      }
    ],
    "type": {
      "id": 3,
      "value": "Tier 3"
    },
    "typeId": 3,
    "variables": []
  },
  "apiManagement": [
    "ApiGee"
  ],
  "available": true,
  "billing": "Monthly: Eagle tier 3",
  "businessUnit": {
    "description": "FICC",
    "id": 3,
    "isActive": true,
    "name": "FICC"
  },
  "businessUnitId": 3,
  "cd": [
    {
      "id": 5,
      "value": "Codeship"
    },
    {
      "id": 6,
      "value": "Option"
    }
  ],
  "ci": [
    {
      "id": 3,
      "value": "Jenkins"
    },
    {
      "id": 5,
      "value": "Travis"
    }
  ],
  "envs": [
    {
      "id": 1,
      "isActive": true,
      "name": "Development"
    }
  ],
  "gitRepoUrl": "",
  "hosting": [
    "Appengine"
  ],
  "id": 1,
  "isActive": true,
  "isFavourite": false,
  "lastUpdated": "2020-05-12 08:29:07",
  "name": "CMS Web App",
  "regions": [
    "UK",
    "DB"
  ],
  "sensitivity": "Public",
  "serverCapacity": 1200,
  "source": "open",
  "sourceControl": {
    "id": 3,
    "value": "GitHub"
  },
  "sourceControlId": 3,
  "status": "Available",
  "technologyOwner": "Sanjeev Gupta",
  "technologyOwnerEmail": "s.gupta@company.name",
  "userCapacity": 1000
}`

**Additional context**
Use 'integration' docker image.

**Comment by Salles-FA** [comment]
-  **Old activator JSON**:
```json
{
  "accessRequestedBy": null,
  "accessRequestedById": null,
  "activator": "Single Region Kubernetes",
  "activatorLink": "",
  "apiManagement": ["ApiGee"],
  "available": true,
  "billing": "Monthly: Eagle tier 3",
  "businessUnit": "FICC Business Unit",
  "category": "Web application",
  "cd": ["Codeship", "Option"],
  "ci": [
    {
      "id": 3,
      "value": "Jenkins"
    },
    {
      "id": 5,
      "value": "Travis"
    }
  ],
  "description": "CMS Web Application activator",
  "envs": ["Development"],
  "gitRepoUrl": "",
  "hosting": ["Appengine"],
  "id": 1,
  "isActive": true,
  "isFavourite": false,
  "lastUpdated": "2020-05-12 08:29:07",
  "name": "CMS Web App",
  "platforms": ["GCP"],
  "regions": ["UK", "DB"],
  "sensitivity": "Public",
  "serverCapacity": 1200,
  "source": "open",
  "sourceControl": ["github"],
  "status": "Available",
  "technologyOwner": "Sanjeev Gupta",
  "technologyOwnerEmail": "s.gupta@company.name",
  "type": "Tier 3",
  "userCapacity": 1000
}
```

 -  **New activator JSON**:
```json
{
  "accessRequestedBy": null,
  "accessRequestedById": null,
  "activator": "Single Region Kubernetes",
  "activatorMetadata": {
    "activatorLink": "",
    "category": "Web application",
    "description": "CMS Web Application activator",
    "id": 1,
    "lastUpdated": "2020-05-12 08:29:07",
    "name": "CMS Web App",
    "platforms": [
      {
        "id": 1,
        "value": "GCP"
      }
    ],
    "type": {
      "id": 3,
      "value": "Tier 3"
    },
    "typeId": 3,
    "variables": []
  },
  "apiManagement": ["ApiGee"],
  "available": true,
  "billing": "Monthly: Eagle tier 3",
  "businessUnit": {
    "description": "FICC",
    "id": 3,
    "isActive": true,
    "name": "FICC"
  },
  "businessUnitId": 3,
  "cd": [
    {
      "id": 5,
      "value": "Codeship"
    },
    {
      "id": 6,
      "value": "Option"
    }
  ],
  "ci": [
    {
      "id": 3,
      "value": "Jenkins"
    },
    {
      "id": 5,
      "value": "Travis"
    }
  ],
  "envs": [
    {
      "id": 1,
      "isActive": true,
      "name": "Development"
    }
  ],
  "gitRepoUrl": "",
  "hosting": ["Appengine"],
  "id": 1,
  "isActive": true,
  "isFavourite": false,
  "lastUpdated": "2020-05-12 08:29:07",
  "name": "CMS Web App",
  "regions": ["UK", "DB"],
  "sensitivity": "Public",
  "serverCapacity": 1200,
  "source": "open",
  "sourceControl": {
    "id": 3,
    "value": "GitHub"
  },
  "sourceControlId": 3,
  "status": "Available",
  "technologyOwner": "Sanjeev Gupta",
  "technologyOwnerEmail": "s.gupta@company.name",
  "userCapacity": 1000
}
```
