### ISSUE TITLE
[BUG] Application's category switch styles bug

### ISSUE THREAD

**Issue by teoMiesiac** [tranquilitybase-io/tb-eagle-console#249]
**Describe the bug**
Application's category switch does not correctly update styles for active view. Logic is working correctly.

1. Go to Solutions
2. Click on Solution's view button
3. Click on Workspace button

**Expected behavior**
Workspace button should switch to active and correctly update styling 

**Screenshots**
![image](https://user-images.githubusercontent.com/21129815/92919845-82028700-f431-11ea-8897-4b7e4c66ba30.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by Salles-FA** [comment]
Hi @teoMiesiac,

This screen is being completely refactored: #244
