### ISSUE TITLE
[Feature] Create Activator step 2 

### ISSUE THREAD

**Issue by teoMiesiac** [tranquilitybase-io/tb-eagle-console#273]
**Is your feature request related to a problem? Please describe.**
As an Admin I want to be able to add optional and mandatory variables to newly created activator

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/21129815/93464946-59273980-f8ea-11ea-90c1-ea6bd16cec1f.png)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Salles-FA** [comment]
tranquilitybase-io/TranquilityBase#47
