### ISSUE TITLE
[Feature] Create Activator step 3

### ISSUE THREAD

**Issue by teoMiesiac** [tranquilitybase-io/tb-eagle-console#287]
**Is your feature request related to a problem? Please describe.**
As an Admin I want to be able to select available environments, CI/CD and available source control for newly created Activator

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/21129815/93871985-cb739180-fccf-11ea-9d9f-b50e4a8e868e.png)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by teoMiesiac** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/47

**Comment by teoMiesiac** [comment]
Admin should be able to add supported regions and business unit

**Comment by andy12838729** [comment]
> Admin should be able to add supported regions and business unit

Admin can only add the regions that are setup in the LZ. For now we only have 1 region available - which is the default the LZ is deployed to. The DAC should know this region. Other regions can be setup in the "Multizone" card.
