### ISSUE TITLE
[Feature] Missing Authorization Bearer Token http header

### ISSUE THREAD

**Issue by teoMiesiac** [tranquilitybase-io/tb-eagle-console#362]
**Is your feature request related to a problem? Please describe.**
Http request should include bearer token.

**Describe the solution you'd like**
Create http interceptor to include bearer token in every API request

**Describe alternatives you've considered**

**Additional context**

**Comment by Salles-FA** [comment]
Duplicated 
 -  https://github.com/tranquilitybase-io/tb-eagle-console/issues/215
