### ISSUE TITLE
[Feature] Allow activators to use Landing Zone environment variables

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-eagle-console#387]
Some of the parameters that activators require are environmental and part of the Landing Zone setup.

Examples of these include:
* Shared VPC
* GCP Region

Activators should declare if they need these variables in their metadata in a 'environment variables' section separate to the current mandatory and optional parameters sections.

DAC will pass all environment variables it is aware of to Jenkins when deploying an activator.

Linked issues:
* https://github.com/tranquilitybase-io/tb-gcp-dac/issues/192
* https://github.com/tranquilitybase-io/tb-gcp-dac/issues/193
* https://github.com/tranquilitybase-io/tb-activator-gft-base/issues/25
* https://github.com/tranquilitybase-io/tb-jenkins-jobs/issues/12

**Comment by Salles-FA** [comment]
Individual tasks are implemented in other repos.
