### ISSUE TITLE
[Feature] Settings view

### ISSUE THREAD

**Issue by teoMiesiac** [tranquilitybase-io/tb-eagle-console#389]
**Is your feature request related to a problem? Please describe.**
As an user I should be able to access settings view and change github account and token.

**Describe the solution you'd like**
- Implement settings view with two inputs: GithubAccount and Password Token. 
- Data should be fetch for and user onInit
- User should be able to edit data

**Describe alternatives you've considered**

**Additional context**

**Comment by Salles-FA** [comment]
@teoMiesiac,

- We've added new "api/settings/" POST, PUT, GET, DELETE methods
- There's no id required
- Make sure the UI is sending Bearer Token within the http reader
- Logged in user must be Admin to have access to this screen and api methods

Regards,
Fábio
