### ISSUE TITLE
[Feature] Shared Service View

### ISSUE THREAD

**Issue by teoMiesiac** [tranquilitybase-io/tb-eagle-console#394]
**Is your feature request related to a problem? Please describe.**
As an Admin I should be able to access Shared Service screen.

**Describe the solution you'd like**
Implement Shared Service Screen. It should be similar to Landing Zone screen.

**Describe alternatives you've considered**

**Additional context**

**Comment by andy12838729** [comment]
I think it might be useful if the shared services screen initialised like the Activator Store - in that it should read a json file from github that sets what services are available like the activator store does.

**Comment by Salles-FA** [comment]
Hi @andy12838729 ,

Yes! We're going to initialize "Administration->Modules Store" from a json like you mentioned (tb-modules-store repo). Once the module is enabled by the Admin in the Modules Store it's going to be available to configure/deploy via "Administration->Shared Services" screen.
