### ISSUE TITLE
[Feature] Prevent user from logging out after 1h

### ISSUE THREAD

**Issue by teoMiesiac** [tranquilitybase-io/tb-eagle-console#396]
**Is your feature request related to a problem? Please describe.**
As an user I should not be logged out after 1h (Using google credentials).

**Describe the solution you'd like**
Refresh google login token

**Describe alternatives you've considered**

**Additional context**

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/76
