### ISSUE TITLE
[Feature] Implement list filtering component

### ISSUE THREAD

**Issue by teoMiesiac** [tranquilitybase-io/tb-eagle-console#400]
**Is your feature request related to a problem? Please describe.**
Filtering component is required for new filtering design for lists.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/21129815/104297606-5bc62400-54c3-11eb-9f88-ee2cea297991.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by Salles-FA** [comment]
Related with issue #429
