### ISSUE TITLE
[Feature] Implement new filtering design for Solutions module

### ISSUE THREAD

**Issue by teoMiesiac** [tranquilitybase-io/tb-eagle-console#401]
**Is your feature request related to a problem? Please describe.**
As an user I would like to see filtering inputs for list views for solutions's module

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/21129815/104297735-7f896a00-54c3-11eb-9f35-b0a5e4ac3589.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by Salles-FA** [comment]
Related with issue #429
