### ISSUE TITLE
[Feature] Filtering design change Activator Module

### ISSUE THREAD

**Issue by teoMiesiac** [tranquilitybase-io/tb-eagle-console#407]
**Is your feature request related to a problem? Please describe.**
As an user I would like to see filtering inputs for list views for activator's module

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/21129815/105339160-aa1ea580-5bdc-11eb-96df-732bd1cb29b9.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by Salles-FA** [comment]
Related with issue #429
