### ISSUE TITLE
[Feature] New screen: List of Landing Zones

### ISSUE THREAD

**Issue by teoMiesiac** [tranquilitybase-io/tb-eagle-console#426]
**Is your feature request related to a problem? Please describe.**
Implement new home screen. 

**Describe the solution you'd like**
Implement hard coded data as home screen. 
<img width="348" alt="aa" src="https://user-images.githubusercontent.com/21129815/105842403-6958cf00-5fd6-11eb-980b-76375ca0f37e.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/93
