### ISSUE TITLE
[Feature] Implement filtering for User's module 

### ISSUE THREAD

**Issue by teoMiesiac** [tranquilitybase-io/tb-eagle-console#433]
**Is your feature request related to a problem? Please describe.**
As an user I would like to see filtering inputs for list views for user's module

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/21129815/106586636-01136b80-6549-11eb-9773-37c4e194c9f7.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by Salles-FA** [comment]
Related with issue #429
