### ISSUE TITLE
[Feature] Make Teams view consistent

### ISSUE THREAD

**Issue by teoMiesiac** [tranquilitybase-io/tb-eagle-console#444]
**Is your feature request related to a problem? Please describe.**
As a User I would like to see the same functionality and layout for team's module as it was done in solution module

**Describe the solution you'd like**
Take Solution's module as an example and make following changes: 
-Implement filtering component
-Remove unused filter component in list view
-Move create button from grid and list view to header  

**Describe alternatives you've considered**

**Additional context**

**Comment by Salles-FA** [comment]
Related with issue #429
