### ISSUE TITLE
[BUG] Activator's list view doesn't filter on category select

### ISSUE THREAD

**Issue by teoMiesiac** [tranquilitybase-io/tb-eagle-console#452]
**Describe the bug**
When User selects category for first time in activator's view it doesn't query list filtered by selected category. 

**To Reproduce**
1. Go to activator store
2. Click on category
3. See error -> full list is displayed

**Expected behavior**
List should be filtered by category 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Salles-FA** [comment]
Related with issue #429
