### ISSUE TITLE
Eagle-Console First Login Default Password 

### ISSUE THREAD

**Issue by jamroks** [tranquilitybase-io/tb-eagle-console#466]
**Describe the bug**

After starting tb-eagle-console localy I can't login in the UI , what is the default login/password ? 

**To Reproduce**
1/  nom install
2/ docker-compose -f docker-compose.experimental.yml up
3/ npm start
4/ launch my browser to : http://localhost:4200
5/ login form appears but I can't login , can't find any default password if it exist what should i use  ? 

**Expected behavior**
Login to the console

**Screenshots**
![Screenshot 2021-02-22 at 11 44 24](https://user-images.githubusercontent.com/357258/108697675-739db880-7503-11eb-8ba7-b56876459860.png)

Is there a default Login / Password ?

**Comment by RDHA-GFT** [comment]
Hi,

The default accounts for the Eagle Console UI are:

![image](https://user-images.githubusercontent.com/62399091/108726253-19aaec00-751f-11eb-9ac3-496891e81b8b.png)

regards

Richard

**Comment by jamroks** [comment]
it works ! Thanks You ! 

Cheers
