### ISSUE TITLE
[Refactoring] Burger menu is misbehaving

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/tb-eagle-console#504]
**What kind of change does this refactoring issue introduce?**
- [ ] Clean Code
- [ ] S.O.L.I.D. principles
- [ ] Performance improvement
- [ ] Complexity reduction
- [ ] Maintainability improvement
- [ ] “Triangular” Code to Flat Code
- [x] Other... Please describe: Layout rework

**Is your refactoring request related to a problem? Please describe.**
Currently the implementation is causing the left sidebar to have a strange behavior on transitions. Also the implementation is hiding the div which purpose is grey out the screen.  

**Describe the solution you'd like**
Implement the burger menu using the standard behavior of the Angular material component.

**Describe alternatives you've considered**
N/A

**Additional context**
The current implementation was based on "YouTube" but they are not using this Angular material component. So to have another example to look at, please check Google Cloud Console.

**Comment by MaciejLit** [comment]
Test
