### ISSUE TITLE
[Feature] Change Activator Store graphic layout to match Landing Zone layout

### ISSUE THREAD

**Issue by ZakkGFT** [tranquilitybase-io/tb-eagle-console#506]
**Is your feature request related to a problem? Please describe.**
Look and feel of Activator Store view doesn't match the Landing Zone view

**Describe the solution you'd like**
Activator Store layout should be the same as in Landing Zone

**Describe alternatives you've considered**

**Additional context**

**Comment by Salles-FA** [comment]
Related with issue #429
