### ISSUE TITLE
[Feature] Edit functionality for solutions

### ISSUE THREAD

**Issue by kwicherska** [tranquilitybase-io/tb-eagle-console#54]
**Is your feature request related to a problem? Please describe.**
Edit functionality is missing.

**Describe the solution you'd like**
Add edit functionality on soultions cards. Add view which display fields that are editable by user and have save (update) option.

**Describe alternatives you've considered**
Add edit functionality, use angular material for UI, add routing and additional view for card in edit mode.

**Additional context**

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/14
