### ISSUE TITLE
Should be able to view which Users have permission to a Solution

### ISSUE THREAD

**Issue by andy12838729** [tranquilitybase-io/tb-eagle-console#63]
Should be able to view which Teams have permission to a Solution - there should be another tab next to Workspace, called Teams, that show the Teams. Should also be able to view the Users in each Team.

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/23

**Comment by Salles-FA** [comment]
This is being modified to have only one TEAM for each solution.

- https://github.com/tranquilitybase-io/tb-eagle-console/issues/124
- https://github.com/tranquilitybase-io/tb-eagle-console/issues/125
- https://github.com/tranquilitybase-io/tb-houston-service/issues/207

**Comment by Salles-FA** [comment]
@Aparad,

This has been modified to have only one team for each solution.

Implementation required now is a team TAB with teamMembers list for solution view screen, next to activators tab.

**Comment by andy12838729** [comment]
It should be possible for more than one team to have access to a solution

**Comment by Salles-FA** [comment]
Done
