### ISSUE TITLE
[Feature] Add internal semantic versioning

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-eagle-console#65]
Same as what is done in the tb-houston-service repo.
- cicd workflow to maintain the version.json file 
- add a tag to the commit.

**Comment by karwootang-gft** [comment]
Hi Richard @RDHA-GFT, 

CC: @Salles-FA, @andy12838729, @sunderhill-gft, @sandyasheri-gft

We have a need of a service account to deploy images and tags to tranquility-base-images, from each of the Repo's Github actions CICD workflows. 

Similar, to the one we have in tb-houston-service: 
![Screenshot 2020-04-20 at 07 58 49](https://user-images.githubusercontent.com/61692208/79724198-07e53080-82df-11ea-95ee-5e59eb4d9931.png)

We also need a github actions service account to commit code within a Github action.

e.g.

        git config user.email **git.action@gft.com**
        git config user.name **"git.action"**
        git add version.json
       git push

Please create, I've checked I don't have the permissions to create. 
I'll let you decide the names.

thanks,
Karwoo

**Comment by RDHA-GFT** [comment]
Hi Scott, Can you take a look at this request as I do not have the required permissions.

The service account is required on the following project:

gcp project: eagle-console-resources
Permissions:
Role: Cloud Build Service Account
+ Storage Admin

Suggested name: tb-github-sa

Regards

Richard

**Comment by karwootang-gft** [comment]
As discussed with Fabio, the CICD workflow will consist of just testing and tagging the code with the internal semantic version number. Will add the building of the images at a later date when the SA account has been created.

**Comment by karwootang-gft** [comment]
@Salles-FA Fabio,

To confirm the changes:

- If a feature branch and it's the first commit, increase minor number.
- if a feature branch and the commit count is greater than one, increase the patch number.

This command will tell you how many commits done in the current branch:
git rev-list --count --no-merges master..

**Comment by Salles-FA** [comment]
For 'feature/' branches and 'minor' value:

- Before creating a PR the DEV user should merge master into this featured branch. 
- The reviewer must check this before approve
- The creation of a 'feature/' branch should increment 'minor' value
- If there are changes during the review process, each 'git push' should increment 'patch' value. (not related to each commit)
- If there is a new master during the reviewing process, either dev or reviewer must merge master updates into this featured branch. At this moment the current 'minor' is incremented again.

This loop should run until the PR is merged into master and it will determine the new version number to be updated in other PRs.

**Comment by stugit** [comment]
> For 'feature/' branches and 'minor' value:
> 
> * Before creating a PR the DEV user should merge master into this featured branch.
> * The reviewer must check this before approve
> * The creation of a 'feature/' branch should increment 'minor' value
> * If there are changes during the review process, each 'git push' should increment 'patch' value. (not related to each commit)
> * If there is a new master during the reviewing process, either dev or reviewer must merge master updates into this featured branch. At this moment the current 'minor' is incremented again.
> 
> This loop should run until the PR is merged into master and it will determine the new version number to be updated in other PRs.

"If there is a new master during the reviewing process, either dev or reviewer must merge master updates into this featured branch. At this moment the current 'minor' is incremented again." - because both the master and the feature branch have changed the version.json this will cause a merge conflict which will need to be resolved manually. Is this acceptable?

**Comment by Salles-FA** [comment]
We must review it in order to avoid SEMVER conflicts. 

The solution we have now is using a file to deal with versioning, this way additional commits are needed, and that's the reason of conflicts. 

It should be only git tags been updated. And SEMVER bot should only be triggered when a PR is effectively merged into master. When triggered it should increment the version number accordingly:
- If it is a 'feature' branch, increment 'minor'. (e.g. v0.10.2 -> v0.11.0)
- if it is a 'major' (with braking changes) branch, increment 'major'. (e.g. v0.11.13 -> v1.0.0)
- otherwise increment 'patch'. (e.g. v0.11.0 -> v0.11.1)

**Comment by karwootang-gft** [comment]
Hi Fabio @Salles-FA  - regarding the semver requirements,  to cater for the way other teams work and maximise flexibility, I’m proposing we use the merge comment to decide how version is increments. For example, if you put in the command “Bug fix #patch”, it will increment the patch number. “New feature #minor” will update the minor number, and similarly for major, "New Major release #major".

So, for your requirement, commits in a feature branch doesn’t increment the version number or create a tag. The tag is only created on the PR merge. 

e.g. For example, in this scenario, the latest dev version is 1.4.7, and we find a bug in version 1.1.2. We would open the code for 1.1.2, fix the bug, update the patch number to create a new release called v1.1.3.
