### ISSUE TITLE
[Feature] Setup automated Web Browser testing when code is pushed to the remote repo

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-eagle-console#68]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when repeating the same manually tests over and over...

**Describe the solution you'd like**
Create a step in a Github action CICD workflow that test the UI automatically.
I propose we use Selenium, as I think it one of the most widely used, it's open source and supports python. https://www.youtube.com/watch?v=_JNeiGbAgL4

**Describe alternatives you've considered**
HP TP, Test Complete, IBM RFT are alternatives, but all require a licence. 
See video https://www.youtube.com/watch?v=_JNeiGbAgL4
We currently manual test, not ideal as it's error prone and time consuming. 
Using an automated testing script is a good investment of our time. 

**Additional context**
Why automatic testing?
https://www.youtube.com/watch?v=5FUdrBq-WFo

**Comment by andy12838729** [comment]
It's a good idea to do this sooner rather than later.

**Comment by karwootang-gft** [comment]
The Python instructions below probably the simplest:
https://www.youtube.com/watch?v=GJjMjB3rkJM&list=TLPQMTkwNDIwMjBaiFoQdSePLA&index=2
