### ISSUE TITLE
[Feature] Add Folder structure selection to the Folder Structure screen 

### ISSUE THREAD

**Issue by andy12838729** [tranquilitybase-io/tb-eagle-console#71]
**Is your feature request related to a problem? Please describe.**
The current problem is that all applications are deployed to Solutions underneath the main Applications folder. Whilst this is ok for an MVP, users will want more flexibility to define their structures and to follow the CSP best practice.

**Describe the solution you'd like**
The user should be able to select more levels to the Applications folder structure.

![Applications Hierachy (2)](https://user-images.githubusercontent.com/53095823/80034612-9bd51900-84e6-11ea-8bd5-78114c594603.png)

**Describe alternatives you've considered**
The alternative is to stick with something simple as we have now, but many users will want to have flexibility here. This issue should also work with the issue created for the Environment selection.\

**Additional context**
Google articles
https://cloud.google.com/docs/enterprise/best-practices-for-enterprise-organizations
https://cloud.google.com/resource-manager/docs/creating-managing-folders

**Comment by Salles-FA** [comment]
Linked issue - tranquilitybase-io/tb-eagle-console#66

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/22

**Comment by Salles-FA** [comment]
There is a limitation to 10 nested folders, as @karwootang-gft and @sunderhill-gft has explained here: 

- https://github.com/tranquilitybase-io/tb-houston-service/issues/114
