### ISSUE TITLE
[Feature] Create Shared Services Cards

### ISSUE THREAD

**Issue by andy12838729** [tranquilitybase-io/tb-eagle-console#86]
**Is your feature request related to a problem? Please describe.**
Currently the Shared Services (Datacenter) tab is empty. 

**Describe the solution you'd like**
The Shared Services tab should have a set of configurable tiles like the Landing Zone. The following entries should exist in the screen:

* Logging
* Alerting
* Monitoring
* Billing
* Security
* Secrets
* DevOps
* ITSM
* Compliance

**Describe alternatives you've considered**
Its possible we could use the existing table structure for Landing Zone, but add a group level to group by Landing Zone or Shared Services (allowing other groups in the future).

**Additional context**

**Comment by Salles-FA** [comment]
Done
